# Generated by Django 2.1 on 2018-08-09 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrapp', '0002_auto_20180809_0325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Главный администратор компании'), ('worker', 'Наемный рабочий'), ('hrworker', 'Работник отдела кадров')], max_length=10)),
                ('vakant', models.CharField(choices=[(True, 'free'), (False, 'busy')], max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='position',
            name='vakant',
            field=models.CharField(choices=[(True, 'free'), (False, 'busy')], max_length=5),
        ),
        migrations.AddField(
            model_name='worker',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrapp.Position'),
        ),
        migrations.AddField(
            model_name='worker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
