# Generated by Django 2.1 on 2018-08-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0003_auto_20180809_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='vakant',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='worker',
            name='vakant',
            field=models.BooleanField(),
        ),
    ]
