# Generated by Django 2.1 on 2018-08-14 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0005_auto_20180809_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='about',
            field=models.CharField(blank=True, max_length=1200, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='worker',
            name='education',
            field=models.CharField(blank=True, max_length=400, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='company',
            name='title_com',
            field=models.CharField(max_length=100, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='departament',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrapp.Company', verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='departament',
            name='title_dep',
            field=models.CharField(max_length=100, verbose_name='Название отдела'),
        ),
        migrations.AlterField(
            model_name='position',
            name='departament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrapp.Departament', verbose_name='Название отдела'),
        ),
        migrations.AlterField(
            model_name='position',
            name='title_pos',
            field=models.CharField(max_length=100, verbose_name='Название должности'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrapp.Position', verbose_name='Название должности'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='role',
            field=models.CharField(choices=[('admin', 'Главный администратор компании'), ('worker', 'Наемный рабочий'), ('hrworker', 'Работник отдела кадров')], max_length=10, verbose_name='Роль работника'),
        ),
    ]
